### ISSUE TITLE
Tab crash on google image search.

### ISSUE THREAD

**Issue by clydo** [pabli24/ultimate-scrollbar#1]
Hello! I have been using your Stylus theme "Dark Minimalistic Scrollbar" version 0.1.3 without any issues until now. However, when I click on "Image" during a Google search, the tab crashes with the following error message: "STATUS_BREAKPOINT." Since I've been using it for a while, I wondered if there was an update to the theme that would solve my problem, and that's how I came across the "new version": Ultimate Scrollbar. Unfortunately, this did not solve my issue...

If I'm the only one experiencing this problem, so be it, but isn't there a "simple" fix other than disabling the theme?

I have no idea what information I could provide to help you, but I'm open to any suggestions, haha!

I also specify that I have conducted tests with all extensions disabled and all Stylus themes deactivated (except yours, of course), i made this GIF capture after to illustrate...
I'm using the latest Brave version.

Edit: Actually, even other tabs like maps/books/... also cause a crash.

![scrollbar](https://github.com/user-attachments/assets/d0c03710-113c-4dca-a8e2-449b7bfaa98c)

**Comment by pabli24** [comment]
I can't reproduce this problem.
It can be google, brave or stylus causing this. There is nothing I can do in the style itself.

You can [exclude the style](https://github.com/pabli24/ultimate-scrollbar/wiki#how-to-exclude-web-pages) just for google com.

Try to reinstall stylus and browser. If it still crashing, maybe open an issue on https://github.com/openstyles/stylus/issues

**Comment by clydo** [comment]
Got it, I'll try to investigate on my end! Thank you for your response!
